import { Images, Layer, UserLocation } from '@maplibre/maplibre-react-native';

import { useDeviceHeading } from '@/map/use-device-heading';

// Source id created by UserLocation's internal LayerAnnotation. Children layers
// reference it so they track the user position automatically.
const SOURCE = 'mlrn-user-location';
const PUCK_IMAGE_ID = 'user-puck';
const PUCK_BLUE = '#2563EB';

// Navigation-arrow puck (blue chevron, white border, soft shadow) generated by
// scripts/generate-user-puck.mjs.
const PUCK_IMAGE = require('@/assets/images/user-puck.png');

/**
 * Current-location marker as a compass-driven navigation-arrow puck (Google-Maps
 * "driving arrow" style): the whole puck is a directional arrow that points
 * where the device is physically facing, even when stationary. Replaces
 * MapLibre's built-in `heading`, which only rotates by GPS course-over-ground
 * and so is meaningless while standing still.
 *
 * Rendered as `UserLocation` children so it tracks position natively. When a
 * compass reading is available the arrow symbol layer is rotated by
 * `useDeviceHeading`; otherwise it falls back to a plain white-ring + blue dot.
 */
export function UserLocationHeading() {
  const heading = useDeviceHeading();

  return (
    <>
      <Images images={{ [PUCK_IMAGE_ID]: PUCK_IMAGE }} />
      <UserLocation>
        {heading != null ? (
          <Layer
            id="mlrn-user-puck"
            type="symbol"
            source={SOURCE}
            layout={{
              'icon-image': PUCK_IMAGE_ID,
              'icon-allow-overlap': true,
              'icon-pitch-alignment': 'map',
              'icon-rotation-alignment': 'map',
              'icon-rotate': heading,
            }}
          />
        ) : (
          <>
            <Layer
              id="mlrn-user-dot-white"
              type="circle"
              source={SOURCE}
              paint={{ 'circle-radius': 9, 'circle-color': '#ffffff', 'circle-pitch-alignment': 'map' }}
            />
            <Layer
              id="mlrn-user-dot-blue"
              type="circle"
              source={SOURCE}
              paint={{ 'circle-radius': 6, 'circle-color': PUCK_BLUE, 'circle-pitch-alignment': 'map' }}
            />
          </>
        )}
      </UserLocation>
    </>
  );
}
